server:
  port: 8380

spring:
  datasource:
    url: jdbc:mysql://172.17.0.2:3306/sample
    username: root
    password: admin
    initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        order_inserts: true
        order_updates: true
      javax:
        persistence:
          sharedCache:
            mode: ALL